name: Daily URL Checker

on:
  schedule:
    - cron: '*/5 * * * *' # 5分おきに実行
  workflow_dispatch: # 手動実行用ボタンを表示

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python main.py
